
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 75
#define YY_END_OF_BUFFER 76
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[217] =
    {   0,
        0,    0,   76,   74,    1,    2,   62,   24,   47,   57,
       73,   63,   64,   45,   43,   69,   44,   74,   46,    3,
       70,   48,   54,   50,   71,   71,   67,   68,   59,   71,
       71,   71,   71,   71,   71,   71,   71,   71,   71,   65,
       58,   66,    1,   53,   24,   23,   24,   55,   73,   19,
       18,   19,   41,   42,    0,    4,    0,   20,   72,   72,
        3,   72,   60,   49,   52,   51,   61,   71,    0,    6,
       71,   71,   71,   71,   71,   71,   29,   71,   71,   71,
       25,   71,   71,   71,   71,   71,   56,   73,    7,    0,
       73,    7,   73,   73,   73,   73,   73,   73,   73,   73,

       73,    5,    5,    4,    0,    0,    0,    0,    0,   20,
       20,   72,    4,   72,    6,    4,    0,    6,   71,   71,
       71,   71,   71,   71,   71,   71,   27,   31,   71,   71,
       71,   71,   15,   17,   16,   10,   14,   11,    8,   13,
        9,   12,    5,    0,    0,    6,    4,   22,   22,    0,
        0,    0,    0,    0,    0,    0,   20,   20,    4,    0,
       71,   38,   32,   71,   71,   71,   26,   71,   71,   71,
       35,   71,    0,    0,    5,    6,    5,    5,    4,   20,
        0,   22,   22,   20,   20,   20,    0,    4,   30,   71,
       71,   71,   33,   71,   71,   28,    0,    5,    5,    5,

        5,   22,    0,    0,    4,   71,   71,   34,   36,   37,
        5,   21,   71,   39,   40,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        4,    4,    5,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    6,    7,    8,    9,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   22,
       22,   22,   22,   22,   22,   22,   22,    9,   23,   24,
       25,   26,    9,    9,   27,   27,   27,   27,   28,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       29,   30,   31,   32,   27,    9,   33,   34,   35,   36,

       37,   38,   27,   39,   40,   27,   41,   42,   27,   43,
       44,   27,   27,   45,   46,   47,   48,   49,   50,   27,
       27,   27,   51,   52,   53,    9,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[54] =
    {   0,
        1,    2,    3,    2,    1,    4,    5,    6,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        7,    7,    4,    5,    5,    5,    7,    7,    5,    5,
        5,    5,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        5,    5,    5
    } ;

static yyconst flex_uint16_t yy_base[233] =
    {   0,
        0,    0,  586,  587,   52,  587,  560,   47,  587,  573,
       58,  587,  587,  587,  567,  587,  563,   45,   53,   50,
      587,   50,  549,   54,    0,   65,  587,  587,  587,  519,
       52,   45,  480,   48,   55,  467,  448,  453,  457,  587,
      438,  587,   95,  587,   86,  587,   99,  587,  587,  107,
      471,  129,  587,  587,   84,   96,  120,  448,   92,  117,
      121,  135,  587,  587,  587,  587,  587,    0,  125,   99,
      142,  437,  424,  433,  419,  418,  407,  406,  403,  399,
        0,  391,  387,  389,  385,  381,  587,  178,  405,  401,
      183,  397,  192,  197,  206,  211,  220,  225,  234,  239,

      248,  147,  170,  226,  240,  261,  265,  269,  284,  376,
      170,  184,  269,  198,  105,  212,  256,  143,  369,  356,
      343,  339,  352,  350,  344,  346,    0,    0,  328,  327,
      332,  323,  352,  345,  343,  339,  332,  328,  325,  321,
      302,  299,  274,  287,  279,  294,  298,  319,  323,  327,
      343,  347,  351,  367,  358,  375,  587,  277,  370,  378,
      253,    0,    0,  239,  217,  215,    0,  195,  169,  142,
        0,  124,  382,  389,  393,  397,  401,  405,  409,  587,
      430,  434,  438,  166,  125,  225,  429,  438,    0,  109,
      106,  108,    0,   89,   71,    0,  442,  446,  450,  454,

      149,  303,   84,  321,  458,   47,   29,    0,    0,    0,
      261,  587,   28,    0,    0,  587,  480,  487,  494,   54,
      501,  505,  512,  519,  526,  533,  540,  547,  554,  561,
      568,  575
    } ;

static yyconst flex_int16_t yy_def[233] =
    {   0,
      216,    1,  216,  216,  216,  216,  216,  217,  216,  216,
      218,  216,  216,  216,  216,  216,  216,  216,  216,  219,
      216,  216,  216,  216,  220,  220,  216,  216,  216,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  216,
      216,  216,  216,  216,  217,  216,  217,  216,  216,  221,
      222,  221,  216,  216,  216,  216,  223,  224,  219,  219,
      219,  219,  216,  216,  216,  216,  216,  220,  216,  216,
       26,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  216,  221,  222,  222,
      221,  222,  221,  221,  221,  221,  221,  221,  221,  221,

      221,  216,  216,  216,  216,  225,  225,  226,  227,  224,
      224,  219,  216,  219,  219,  216,  216,  216,  220,  220,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      220,  220,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  216,  216,  216,  216,  216,  225,  225,  227,
      226,  228,  225,  225,  226,  229,  216,  230,  216,  216,
      220,  220,  220,  220,  220,  220,  220,  220,  220,  220,
      220,  220,  216,  216,  216,  216,  216,  216,  216,  216,
      226,  225,  225,  231,  230,  230,  216,  216,  220,  220,
      220,  220,  220,  220,  220,  220,  216,  216,  216,  216,

      216,  231,  232,  231,  216,  220,  220,  220,  220,  220,
      216,  216,  220,  220,  220,    0,  216,  216,  216,  216,
      216,  216,  216,  216,  216,  216,  216,  216,  216,  216,
      216,  216
    } ;

static yyconst flex_uint16_t yy_nxt[641] =
    {   0,
        4,    5,    6,    5,    5,    5,    7,    8,    4,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       20,   20,   21,   22,   23,   24,   25,   26,   27,    4,
       28,   29,   25,   30,   31,   32,   33,   34,   25,   35,
       25,   25,   25,   25,   36,   37,   25,   25,   38,   39,
       40,   41,   42,   43,   46,   43,   43,   43,   49,   49,
       68,   49,   49,   55,  215,   56,   56,   57,   60,   51,
       61,   61,   58,   63,   64,  214,   47,   62,   66,   67,
       69,   76,   69,   70,   73,   71,   71,   52,   77,   79,
       74,   80,   81,   46,  213,   75,   43,   82,   43,   43,

       43,   45,   55,  212,  102,  102,   46,   49,   49,  210,
       49,   49,  216,  216,  103,   47,  104,  104,   89,  118,
      118,  107,  107,  105,  107,  118,  118,  108,   47,   49,
       49,  209,   49,   49,  109,  112,   91,  113,  113,   60,
       92,   61,   61,   70,  208,  117,  117,  207,   62,   93,
      114,  206,  114,  115,  186,  116,  116,  216,   94,  216,
      196,   95,   96,  118,  118,  103,   97,  143,  143,  201,
      201,   98,  158,   99,  144,  100,  195,  101,   49,   49,
      203,   49,   49,   49,   49,  204,   49,   49,  103,   51,
      143,  143,   49,   49,  133,   49,   49,   49,   49,  111,

       49,   49,  112,  134,  102,  102,   49,   49,  135,   49,
       49,   49,   49,  194,   49,   49,  115,  136,  116,  116,
       49,   49,  137,   49,   49,   49,   49,  158,   49,   49,
       70,  138,  116,  116,   49,   49,  139,   49,   49,   49,
       49,  193,   49,   49,  103,  140,  104,  104,   49,   49,
      141,   49,   49,  105,  186,  145,  192,  145,  146,  142,
      147,  147,  149,  149,  191,  149,  149,  149,  108,  149,
      151,  151,  108,  151,   70,  150,  117,  117,  190,  150,
      106,  211,  211,  152,  106,  154,  154,  103,  154,  159,
      159,  155,  103,  189,  143,  143,  160,  176,  156,  147,

      147,  144,  173,  157,  173,  174,  186,  175,  175,  173,
       51,  173,  174,   51,  177,  177,  178,  203,  179,  179,
      149,  149,  204,  149,  149,  149,  108,  149,  154,  154,
      108,  154,   51,  150,  155,  203,   51,  150,  106,   51,
      204,  156,  106,   51,  151,  151,  180,  151,  181,  181,
       51,  181,  149,  149,   51,  149,   51,  152,  108,  151,
      151,  152,  151,   51,  172,  150,  157,  171,  149,  149,
      106,  149,  152,  170,  108,  169,  183,  183,  168,  183,
      167,  150,  155,  166,  165,  164,  106,  163,  103,  150,
      159,  159,  162,  187,  184,  187,  146,  160,  188,  188,

      197,  161,  175,  175,  173,  111,  173,  174,   51,  175,
      175,  198,   51,  199,  199,  197,   51,  177,  177,  198,
      132,  200,  200,  198,  131,  201,  201,  178,  130,  179,
      179,  151,  151,  129,  151,  149,  149,  128,  149,  149,
      149,  108,  149,  127,  152,  108,  126,  176,  150,  188,
      188,  125,  150,  106,  124,  123,  178,  106,  205,  205,
      197,  122,  175,  175,  198,  121,  211,  211,  198,  120,
      199,  199,  198,  119,  200,  200,  178,  111,  205,  205,
       45,   45,   51,   45,   45,   45,   45,   50,   50,   87,
       50,   50,   50,   50,   59,   86,   85,   84,   59,   59,

       59,   88,   88,   83,   88,   88,   88,   88,   90,   90,
       90,   90,  106,  106,  106,  106,  106,  106,  106,  110,
      110,   78,  110,  110,  110,  110,  148,  148,  148,  148,
      148,  148,  148,  108,  108,  108,  108,  108,  108,  108,
      153,  153,  153,  153,  153,  153,  153,  155,  155,  155,
      155,  155,  155,  155,  182,  182,  182,  182,  182,  182,
      182,  185,  185,   72,  185,  185,  185,  185,  202,  202,
      202,  202,  202,   65,  202,  204,  204,  204,  204,  204,
       54,  204,   53,   48,   44,  216,    3,  216,  216,  216,
      216,  216,  216,  216,  216,  216,  216,  216,  216,  216,

      216,  216,  216,  216,  216,  216,  216,  216,  216,  216,
      216,  216,  216,  216,  216,  216,  216,  216,  216,  216,
      216,  216,  216,  216,  216,  216,  216,  216,  216,  216,
      216,  216,  216,  216,  216,  216,  216,  216,  216,  216
    } ;

static yyconst flex_int16_t yy_chk[641] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    5,    8,    5,    5,    5,   11,   11,
      220,   11,   11,   18,  213,   18,   18,   19,   20,   11,
       20,   20,   19,   22,   22,  207,    8,   20,   24,   24,
       26,   32,   26,   26,   31,   26,   26,   11,   32,   34,
       31,   34,   35,   45,  206,   31,   43,   35,   43,   43,

       43,   47,   55,  203,   55,   55,   47,   50,   50,  195,
       50,   50,   59,   59,   56,   45,   56,   56,   50,   70,
       70,   57,   57,   56,   57,  115,  115,   57,   47,   52,
       52,  194,   52,   52,   57,   60,   52,   60,   60,   61,
       52,   61,   61,   69,  192,   69,   69,  191,   61,   52,
       62,  190,   62,   62,  185,   62,   62,   71,   52,   71,
      172,   52,   52,  118,  118,  102,   52,  102,  102,  201,
      201,   52,  111,   52,  102,   52,  170,   52,   88,   88,
      184,   88,   88,   91,   91,  184,   91,   91,  103,   88,
      103,  103,   93,   93,   91,   93,   93,   94,   94,  111,

       94,   94,  112,   93,  112,  112,   95,   95,   94,   95,
       95,   96,   96,  169,   96,   96,  114,   95,  114,  114,
       97,   97,   96,   97,   97,   98,   98,  186,   98,   98,
      116,   97,  116,  116,   99,   99,   98,   99,   99,  100,
      100,  168,  100,  100,  104,   99,  104,  104,  101,  101,
      100,  101,  101,  104,  186,  105,  166,  105,  105,  101,
      105,  105,  106,  106,  165,  106,  107,  107,  106,  107,
      108,  108,  107,  108,  117,  106,  117,  117,  164,  107,
      106,  211,  211,  108,  107,  109,  109,  113,  109,  113,
      113,  109,  143,  161,  143,  143,  113,  145,  109,  145,

      145,  143,  144,  109,  144,  144,  158,  144,  144,  146,
      142,  146,  146,  141,  146,  146,  147,  202,  147,  147,
      148,  148,  202,  148,  149,  149,  148,  149,  150,  150,
      149,  150,  140,  148,  150,  204,  139,  149,  148,  138,
      204,  150,  149,  137,  151,  151,  150,  151,  152,  152,
      136,  152,  153,  153,  135,  153,  134,  151,  153,  155,
      155,  152,  155,  133,  132,  153,  152,  131,  154,  154,
      153,  154,  155,  130,  154,  129,  156,  156,  126,  156,
      125,  154,  156,  124,  123,  122,  154,  121,  159,  156,
      159,  159,  120,  160,  156,  160,  160,  159,  160,  160,

      173,  119,  173,  173,  174,  110,  174,  174,   92,  174,
      174,  175,   90,  175,  175,  176,   89,  176,  176,  177,
       86,  177,  177,  178,   85,  178,  178,  179,   84,  179,
      179,  181,  181,   83,  181,  182,  182,   82,  182,  183,
      183,  182,  183,   80,  181,  183,   79,  187,  182,  187,
      187,   78,  183,  182,   77,   76,  188,  183,  188,  188,
      197,   75,  197,  197,  198,   74,  198,  198,  199,   73,
      199,  199,  200,   72,  200,  200,  205,   58,  205,  205,
      217,  217,   51,  217,  217,  217,  217,  218,  218,   41,
      218,  218,  218,  218,  219,   39,   38,   37,  219,  219,

      219,  221,  221,   36,  221,  221,  221,  221,  222,  222,
      222,  222,  223,  223,  223,  223,  223,  223,  223,  224,
      224,   33,  224,  224,  224,  224,  225,  225,  225,  225,
      225,  225,  225,  226,  226,  226,  226,  226,  226,  226,
      227,  227,  227,  227,  227,  227,  227,  228,  228,  228,
      228,  228,  228,  228,  229,  229,  229,  229,  229,  229,
      229,  230,  230,   30,  230,  230,  230,  230,  231,  231,
      231,  231,  231,   23,  231,  232,  232,  232,  232,  232,
       17,  232,   15,   10,    7,    3,  216,  216,  216,  216,
      216,  216,  216,  216,  216,  216,  216,  216,  216,  216,

      216,  216,  216,  216,  216,  216,  216,  216,  216,  216,
      216,  216,  216,  216,  216,  216,  216,  216,  216,  216,
      216,  216,  216,  216,  216,  216,  216,  216,  216,  216,
      216,  216,  216,  216,  216,  216,  216,  216,  216,  216
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "1505044_flex.l"
#line 6 "1505044_flex.l"

#include"1505044symbolTable.h"
#include"y.tab.h"



int line_count=1;
//int currentpos=0;
int err=0;
//int sizeable;
//int ind;
//int bucketcnt;
//int in=0;


//FILE *logout;
//FILE *tokenout;
//string s;


#line 705 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 68 "1505044_flex.l"

#line 925 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 217 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 587 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 69 "1505044_flex.l"
{}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 70 "1505044_flex.l"
{line_count++;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 72 "1505044_flex.l"
{
				SymbolInfo* str=new SymbolInfo(yytext,"CONST_INT");
				yylval.symbolVal=str;
				return CONST_INT;
		}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 78 "1505044_flex.l"
{	
				SymbolInfo* str= new SymbolInfo(yytext,"CONST_FLOAT");
				yylval.symbolVal=str;
				return CONST_FLOAT;
			}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 85 "1505044_flex.l"
{	err++;
			
			}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 89 "1505044_flex.l"
{	err++;
			
			}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 93 "1505044_flex.l"
{		SymbolInfo* str= new SymbolInfo(yytext,"CONST_CHAR");
				yylval.symbolVal=str;
				return CONST_CHAR;
		}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 99 "1505044_flex.l"
{			yytext[0]='\n';
				yytext[1]='\0';
				SymbolInfo* str= new SymbolInfo(yytext,"CONST_CHAR");
				yylval.symbolVal=str;
				return CONST_CHAR;
		}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 106 "1505044_flex.l"
{			yytext[0]='\t';
				yytext[1]='\0';
				SymbolInfo* str= new SymbolInfo(yytext,"CONST_CHAR");
				yylval.symbolVal=str;
				return CONST_CHAR;
		}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 113 "1505044_flex.l"
{			yytext[0]='\a';
				yytext[1]='\0';
				SymbolInfo* str= new SymbolInfo(yytext,"CONST_CHAR");
				yylval.symbolVal=str;
				return CONST_CHAR;
		}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 120 "1505044_flex.l"
{			yytext[0]='\f';
				yytext[1]='\0';
				SymbolInfo* str= new SymbolInfo(yytext,"CONST_CHAR");
				yylval.symbolVal=str;
				return CONST_CHAR;
		}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 127 "1505044_flex.l"
{			yytext[0]='\v';
				yytext[1]='\0';
				SymbolInfo* str= new SymbolInfo(yytext,"CONST_CHAR");
				yylval.symbolVal=str;
				return CONST_CHAR;
		}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 134 "1505044_flex.l"
{			yytext[0]='\v';
				yytext[1]='\0';
				SymbolInfo* str= new SymbolInfo(yytext,"CONST_CHAR");
				yylval.symbolVal=str;
				return CONST_CHAR;
		}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 141 "1505044_flex.l"
{			yytext[0]='\b';
				yytext[1]='\0';
				SymbolInfo* str= new SymbolInfo(yytext,"CONST_CHAR");
				yylval.symbolVal=str;
				return CONST_CHAR;
		}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 147 "1505044_flex.l"
{			yytext[0]='\"';
				yytext[1]='\0';
				SymbolInfo* str= new SymbolInfo(yytext,"CONST_CHAR");
				yylval.symbolVal=str;
				return CONST_CHAR;
		}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 153 "1505044_flex.l"
{			yytext[0]='\\';
				yytext[1]='\0';
				SymbolInfo* str= new SymbolInfo(yytext,"CONST_CHAR");
				yylval.symbolVal=str;
				return CONST_CHAR;
		}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 160 "1505044_flex.l"
{			
				SymbolInfo* str= new SymbolInfo(yytext,"CONST_CHAR");
				yylval.symbolVal=str;
				return CONST_CHAR;
		}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 166 "1505044_flex.l"
{	err++;
			
			}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 170 "1505044_flex.l"
{err++;
			
		}
	YY_BREAK
case 20:
/* rule 20 can match eol */
YY_RULE_SETUP
#line 176 "1505044_flex.l"
{
			
			for(int i=0;i<yyleng;i++){	
				if(yytext[i]=='\n') line_count++;
					}
			return COMMENT; 
		}
	YY_BREAK
case 21:
/* rule 21 can match eol */
YY_RULE_SETUP
#line 185 "1505044_flex.l"
{
			for(int i=0;i<yyleng;i++){	
				if(yytext[i]=='\n') line_count++;
					}
			return COMMENT; 
		}
	YY_BREAK
case 22:
/* rule 22 can match eol */
YY_RULE_SETUP
#line 193 "1505044_flex.l"
{	
			for(int i=0;i<yyleng;i++){
				if(yytext[i] == '\n') line_count++;
					}
			err++;

			}
	YY_BREAK
case 23:
/* rule 23 can match eol */
YY_RULE_SETUP
#line 201 "1505044_flex.l"
{

        char *stri = new char[1000];
        //fprintf(logout,"%s\n",yytext);
        int ln = strlen(yytext),i,j;
        for(i=1,j=0;i<ln-1;){

            if(yytext[i]!='\\' || (yytext[i]=='\\' && i==ln-2)){

                stri[j] = yytext[i];
                i++;
                j++;
            }
            else if(yytext[i]=='\\' && yytext[i+1]=='\n'){

                i+=2;
            }
            else{

                if(yytext[i+1]=='n'){

                    stri[j] = '\n';

                }

                    else if(yytext[i+1]=='t'){

                    stri[j] = '\t';

                }

                else if(yytext[i+1]=='\\'){

                    stri[j] = '\\';

                }

                else if(yytext[i+1]=='a'){

                    stri[j] = '\a';

                }

                else if(yytext[i+1]=='f'){

                    stri[j] = '\f';

                }

                else if(yytext[i+1]=='v'){

                    stri[j] = '\v';

                }

                else if(yytext[i+1]=='r'){

                    stri[j] = '\r';

                }

                else if(yytext[i+1]=='b'){

                    stri[j] = '\b';

                }
                i+=2;
                j++;

            }
        }
        	stri[j]='\0';
        	SymbolInfo* str= new SymbolInfo(stri,"String");
		yylval.symbolVal=str;
		return STRING;
}
	YY_BREAK
case 24:
/* rule 24 can match eol */
YY_RULE_SETUP
#line 278 "1505044_flex.l"
{
			for(int i=0;i<yyleng;i++){
				if(yytext[i] == '\n') line_count++;
					}
			err++;

			}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 287 "1505044_flex.l"
{
			return IF;
		}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 292 "1505044_flex.l"
{
			return ELSE;

		}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 297 "1505044_flex.l"
{		return FOR;
		}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 300 "1505044_flex.l"
{		return WHILE;

		}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 304 "1505044_flex.l"
{		return DO;
		}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 307 "1505044_flex.l"
{		return BREAK;

		}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 311 "1505044_flex.l"
{		return INT;

		}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 315 "1505044_flex.l"
{		return CHAR;
		}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 318 "1505044_flex.l"
{		return FLOAT;
		}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 320 "1505044_flex.l"
{		return DOUBLE;
		}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 323 "1505044_flex.l"
{		return VOID;

		}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 327 "1505044_flex.l"
{ 		return RETURN;

		}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 331 "1505044_flex.l"
{		return SWITCH;
		}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 334 "1505044_flex.l"
{		return CASE;
		}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 337 "1505044_flex.l"
{		return DEFAULT;

		}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 341 "1505044_flex.l"
{		return CONTINUE;
		}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 346 "1505044_flex.l"
{		return INCOP;
		}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 349 "1505044_flex.l"
{		return DECOP;
		}
	YY_BREAK
case 43:
#line 353 "1505044_flex.l"
case 44:
YY_RULE_SETUP
#line 354 "1505044_flex.l"
{
			SymbolInfo* str= new SymbolInfo(yytext,"ADDOP");
			yylval.symbolVal=str;
			return ADDOP;
		}
	YY_BREAK
case 45:
#line 361 "1505044_flex.l"
case 46:
#line 362 "1505044_flex.l"
case 47:
YY_RULE_SETUP
#line 362 "1505044_flex.l"
{		
			SymbolInfo* str= new SymbolInfo(yytext,"MULOP");
			yylval.symbolVal=str;
			return MULOP;
		}
	YY_BREAK
case 48:
#line 371 "1505044_flex.l"
case 49:
#line 372 "1505044_flex.l"
case 50:
#line 373 "1505044_flex.l"
case 51:
#line 374 "1505044_flex.l"
case 52:
#line 375 "1505044_flex.l"
case 53:
YY_RULE_SETUP
#line 375 "1505044_flex.l"
{		
			SymbolInfo* str= new SymbolInfo(yytext,"RELOP");
			yylval.symbolVal=str;		
			return RELOP;
		}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 381 "1505044_flex.l"
{		return ASSIGNOP;
		}
	YY_BREAK
case 55:
#line 385 "1505044_flex.l"
case 56:
YY_RULE_SETUP
#line 385 "1505044_flex.l"
{
			SymbolInfo* str= new SymbolInfo(yytext,"LOGICOP");
			yylval.symbolVal=str;		
			return LOGICOP;
		}
	YY_BREAK
case 57:
#line 392 "1505044_flex.l"
case 58:
#line 393 "1505044_flex.l"
case 59:
#line 394 "1505044_flex.l"
case 60:
#line 395 "1505044_flex.l"
case 61:
YY_RULE_SETUP
#line 395 "1505044_flex.l"
{		return BITOP;
		}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 398 "1505044_flex.l"
{		return NOT;
		}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 401 "1505044_flex.l"
{		return LPAREN;
		}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 404 "1505044_flex.l"
{		return RPAREN;
		}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 407 "1505044_flex.l"
{		return LCURL;
		}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 410 "1505044_flex.l"
{		return RCURL;
		}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 413 "1505044_flex.l"
{		return LTHIRD;
		}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 416 "1505044_flex.l"
{		return RTHIRD;
		}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 419 "1505044_flex.l"
{		return COMMA;
		}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 422 "1505044_flex.l"
{		return SEMICOLON;
		}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 427 "1505044_flex.l"
{		SymbolInfo* str= new SymbolInfo(yytext,"ID");
				yylval.symbolVal=str;
				return ID;
			}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 438 "1505044_flex.l"
{	err++;
			//fprintf(logout,"Line no %d and Error: INVALID SUFFIX %s \n",line_count,yytext);
			}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 444 "1505044_flex.l"
{		err++;
			//fprintf(logout,"Line no %d and Error: UNFINISHED CHARACTER %s \n",line_count,yytext);
			}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 448 "1505044_flex.l"
{		err++;
			//fprintf(logout,"Line no %d and Error: UNRECOGNIZED CHARACTER %s \n",line_count,yytext);
			}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 451 "1505044_flex.l"
ECHO;
	YY_BREAK
#line 1553 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 217 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 217 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 216);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 451 "1505044_flex.l"



